*- ----------------------------------------------------------------------------------------------------------------------- -*
*- TR 1009452 - 03/15/05 - Bruno DIEPENDAELE
*- 3/28/05 - EasyPlug formatting added by Michael J. Sabal, Notations.
*- DESCRIPTION: This is a 3 part label designed without the Visual Foxpro label designer. The label is generated by
*- this Foxpro program NOTCBKUC.PRG (orig: NOTPCLUC.PRG)
*- Formatting codes are Avery Dennison EASYPLUG.
*- This label is a 3 part label:
*- PART 1: Carton Pick Slip Internal - this is a carton content list showing the buckets horizontaly
*- PART 2: Christopher & Banks carton content label: Bulk packing (single size per carton)
*- PART 3: Christopher & Banks special carton marking label (08/24/09)
*- ----------------------------------------------------------------------------------------------------------------------- -*
LOCAL lnIndLineBlock1,lnIndLineBlock2,lnIndLineBlock3
LOCAL lnOrgArea
LOCAL lnPageNum, lnLineNum, lnOffset
LOCAL lcShipTo
LOCAL lcDivision,lcStyle,lcFieldName,lnIndbucket,lcIndbucket, lnAggVal
*--- TR 1012146 - 07/27/05 - BD - Modification 1 = Add variaable declaration
LOCAL lcCurSize_code
*=== TR 1012146 - BD - End of modification 1
*--- TR 1012882 - 08/30/05 - BD - Order by Style Modification 1 = Add variable declaration
LOCAL lcSortStyle
*=== TR 1012882 - 08/30/05 - BD - End of Order by Style Modification 1

#DEFINE MaxNbLineBlock1 8
#DEFINE MaxNbLineBlock2 8
#DEFINE MaxNbLineBlock3 20
#DEFINE CRLF CHR(13)+CHR(10)

lnOrgArea=SELECT()
lcOrgAlias=ALIAS()

*- Send data to output
*set device to screen
*set device to file c:\temp\notrlzuc.txt


*!*	************ TEST
*!*	set device to print
*!*	set printer to
*!*	set printer font 'Arial',6 STYLE 'BI'
*!*	??? " "
*!*	for lnInd=1 to 500
*!*		@lnInd,1 say 'Bruno test printing line'+str(lnInd)
*!*	endfor
*!*	set device to screen
*!*	set printer to
*!*	***************

*- -------------------
*- TURN ON the printer
*- -------------------
*SET DEVICE TO PRINT
* SET PRINTER TO
*set printer font 'Courier',6 STYLE 'BI'

*--- ------------------------------------------------------------------------------------------------------------------
*--- TR 1012882 - 08/30/05 - BD - Order by Style Modification 2  
*--- Bruno DIEPENDAELE -> Mike Sabal = This is a block code change

*- First create field SortStyle = this field is used to sort the cursor by style; when there are more than 
*- one style in one carton, SortStyle contains the first style for all records of this carton.
select *, style as SortStyle from (lcOrgAlias) into cursor curSortStyleTemp
MakeCursorWritable('curSortStyleTemp','curSortStyle')
select carton_num from (lcOrgAlias) into cursor curCartonList group by carton_num
SCAN
	SELECT style,carton_num from (lcOrgAlias) WHERE carton_num=curCartonList.carton_num INTO CURSOR curOneCarton ORDER BY style
	*- Take first style in alpha order as the SortStyle
	lcSortStyle=curOneCarton.style
	replace SortStyle WITH lcSortStyle FOR carton_num=curCartonList.carton_num IN curSortStyle
ENDSCAN
IF USED('curOneCarton')
	USE IN curOneCarton
ENDIF
USE IN curCartonList

*- Create cursor curGroupByCarton = list of carton ordered by customer,SortStyle,carton_num
*- This cursor is defining the label sequencing
select Customer,SortStyle,Carton_num from curSortStyle into cursor curGroupByCarton ;
 	   group by customer,SortStyle,carton_num ORDER BY customer,SortStyle,carton_num
SCAN

*- Group by carton_num
*select * from (lcOrgAlias) into cursor curGroupByCarton group by carton_num
*SCAN
*==== TR 1012882 - 08/30/05 - BD - End of Order by Style Modification 2 

*- **************************
*- Build PART 1 of the label
*- **************************
*- --------------------------------------------------------------------------------------------------
*- Create cursor CurPart1 
*- --------------------------------------------------------------------------------------------------
*--- TR 1012146 - 07/27/05 - BD - Modification 2 = Add space(3) as size_code in the SQL
*--- Bruno DIEPENDAELE -> Mike Sabal = This is a block code change
lcCurPrintFinalTemp = GetUniqueFileName()
SELECT *, ;
 SPACE(3) as size_code,;
 space(1) as record_type,;
 space(7) as siz01_head,space(7) as siz02_head,space(7) as siz03_head,space(7) as siz04_head,;
 space(7) as siz05_head,space(7) as siz06_head,space(7) as siz07_head,space(7) as siz08_head,;
 space(7) as siz09_head,space(7) as siz10_head,space(7) as siz11_head,space(7) as siz12_head,;
 space(7) as siz13_head,space(7) as siz14_head,space(7) as siz15_head,space(7) as siz16_head,;
 space(7) as siz17_head,space(7) as siz18_head,space(7) as siz19_head,space(7) as siz20_head,;
 space(7) as siz21_head,space(7) as siz22_head,space(7) as siz23_head,space(7) as siz24_head,;
 9999999 as siz01_qty,9999999 as siz02_qty,9999999 as siz03_qty,9999999 as siz04_qty,;
 9999999 as siz05_qty,9999999 as siz06_qty,9999999 as siz07_qty,9999999 as siz08_qty,;
 9999999 as siz09_qty,9999999 as siz10_qty,9999999 as siz11_qty,9999999 as siz12_qty,;
 9999999 as siz13_qty,9999999 as siz14_qty,9999999 as siz15_qty,9999999 as siz16_qty,;
 9999999 as siz17_qty,9999999 as siz18_qty,9999999 as siz19_qty,9999999 as siz20_qty,;
 9999999 as siz21_qty,9999999 as siz22_qty,9999999 as siz23_qty,9999999 as siz24_qty;
FROM (lcOrgAlias) ;
where .F. ; 
INTO CURSOR CurPart1Temp
*=== TR 1012146 - BD - End of modification 2

MakeCursorWritable('CurPart1Temp','CurPart1')


*- Fill CurPart1 cursor
*- --------------------
*--- TR 1012146 - 07/27/05 - BD - Modification 3 = order cursor cur1GroupBySKU by size_code,style
*--- Bruno DIEPENDAELE -> Mike Sabal = This is a block code change
IF TYPE('&lcOrgAlias..size_code')='U'
	select *, vl_stylr(Division, 'size_code', '',Style) as size_code from (lcOrgAlias) ;
	where carton_num=curGroupByCarton.carton_num ;
	into cursor cur1GroupBySKUTemp
ELSE
	select * from (lcOrgAlias) ;
	where carton_num=curGroupByCarton.carton_num ;
	into cursor cur1GroupBySKUTemp
ENDIF

select * from cur1GroupBySKUTemp where carton_num=curGroupByCarton.carton_num ;
into cursor cur1GroupBySKU group by carton_num,style,color_code,lbl_code ;
ORDER BY carton_num,size_code,style

USE IN cur1GroupBySKUTemp
SELECT cur1GroupBySKU
*=== TR 1012146 - BD - End of modification 3
scan
	select * from (lcOrgAlias) where carton_num=cur1GroupBySKU.carton_num AND style=cur1GroupBySKU.style AND ;
	color_code=cur1GroupBySKU.color_code AND lbl_code=cur1GroupBySKU.lbl_code ;
	into cursor curOneSKU
	*- Add one new record per style
	SCATTER memvar MEMO
	insert into CurPart1 from MEMVAR	
	*- Fill size header fields siz01_head,..,siz09_head	
	*- ------------------------------------------------
	lcDivision=cur1GroupBySKU.division
	lcStyle=cur1GroupBySKU.style
	lcSize_Code = vl_stylr(lcDivision, 'size_code', '',lcStyle)
	lcStyleName = vl_stylr(lcDivision, 'style_name','',lcStyle)
	*--- TR 1012146 - 07/27/05 - BD - Modification 4 = record size_code	in in CurPart1 cursor
	*--- Bruno DIEPENDAELE -> Mike Sabal = This is a new code line
	replace size_code WITH lcSize_Code in CurPart1
	*=== TR 1012146 - BD - End of modification 4	

	vl_sizer(lcDivision,'','curSizeHeader',lcSize_Code)
	for lnIndbucket = 1 to 9
		lcIndbucket=TRANS(lnIndbucket , "@L 99") 
		*- Size header for this bucket = new fields size01_head,..,size22_head
		lcFieldName = "size" + lcIndbucket
		replace siz&lcIndbucket._head with padc(allt(eval('curSizeHeader.' + lcFieldName)), 7) in CurPart1
	endfor	&& End for 9
	
	*- Fill size quantities fields siz01_qty,..,siz09_qty	
	*- --------------------------------------------------
	select curOneSKU
	scan
		lnIndbucket=curOneSKU.sizebucket
		lcIndbucket=TRANS(lnIndbucket,"@L 99")
		*- Fill in siz01_head,..,siz24_head field
		*replace siz&lcIndbucket._head with padc(allt(eval('curOneSKU.size_desc')),7) in CurPart1
		*- Fill in siz01_qty,..,siz24_qty field
		lnAggVal = CurPart1.siz&lcIndbucket._qty + curOneSKU.total_qty
		replace siz&lcIndbucket._qty with lnAggVal in CurPart1
	endscan
endscan

*- Initialize AD Printer controls
??? "#!A1#IMS203.2/238.0" && 8" wide by 9" long "Page"
??? "#ERN1"   
lnPageNum = 0                    && Each 3" page = 79mm, not 76.2mm
lnLinenum = 1

*- Build data string to be printed
*- -------------------------------
select curPart1
go top
*browse title alias()

lnTotalBlockQty=0

*--- TR 1012146 - 07/27/05 - BD - Modification 5 = initialize lcCurSize_code variable
*--- Bruno DIEPENDAELE -> Mike Sabal = This is a new code line
lcCurSize_code=''
*=== TR 1012146 - BD - End of modification 5	

DO WHILE NOT EOF('curPart1') 

	lnIndLineBlock1=0
	lcStringBlock1=''
	lnPageNum = lnPageNum + 1
	lnOffset = (lnPageNum - 1) * 79

	*- Header line 1
	lcStringBlock1=lcStringBlock1+'#T138.0#J05.0#YT107/2///'+'Notations Carton Pick Slip (Internal)'+'#G'
	lcStringBlock1=lcStringBlock1+'#T50.0#J05.0#YT107/2///'+allt(carton_udf1)+'#G'
	lnIndLineBlock1=lnIndLineBlock1+1

	*- Header line 2
	*lcStringBlock1=lcStringBlock1+SPACE(5)
	lcStringBlock1=lcStringBlock1+'#T200.0#J'+str(lnOffset+8)+'#YT103/2///'+'Customer:'+'#G'
	lcStringBlock1=lcStringBlock1+'#T185.0#J'+str(lnOffset+8)+'#YT103/2///'+left(sfscust_name,12)+'#G'
	lcStringBlock1=lcStringBlock1+'#T157.0#J'+str(lnOffset+8)+'#YT103/2///'+'DC ##:'+'#G'
	lcStringBlock1=lcStringBlock1+'#T150.0#J'+str(lnOffset+8)+'#YT103/2///'+allt(center_code)+'#G'
	lcStringBlock1=lcStringBlock1+'#T130.0#J'+str(lnOffset+8)+'#YT103/2///'+'Store ##:'+'#G'
	lcStringBlock1=lcStringBlock1+'#T110.0#J'+str(lnOffset+8)+'#YT103/2///'+left(store,12)+'#G'
	lcStringBlock1=lcStringBlock1+'#T66.6#J'+str(lnOffset+8)+'#YT103/2///'+'Notations Order ##:'+'#G'
	lcStringBlock1=lcStringBlock1+'#T33.3#J'+str(lnOffset+8)+'#YT103/2///'+left(allt(str(ord_num)),15)+'#G'

	*- Header line 3
	*lcStringBlock1=lcStringBlock1+SPACE(5)
	lcStringBlock1=lcStringBlock1+'#T200.0#J'+str(lnOffset+12)+'#YT103/2///'+'Dept:'+'#G'
	lcStringBlock1=lcStringBlock1+'#T185.0#J'+str(lnOffset+12)+'#YT103/2///'+left(department,5)+'#G'
	lcStringBlock1=lcStringBlock1+'#T165.0#J'+str(lnOffset+12)+'#YT103/2///'+'Wave number:'+'#G'
        if wave_num > 0 then
  	  lcStringBlock1=lcStringBlock1+'#T150.0#J'+str(lnOffset+12)+'#YT103/2///'+str(wave_num)+'#G'
        else
  	  lcStringBlock1=lcStringBlock1+'#T150.0#J'+str(lnOffset+12)+'#YT103/2///'+allt(carton_udf2)+'#G'
        endif
	lcStringBlock1=lcStringBlock1+'#T130.0#J'+str(lnOffset+12)+'#YT103/2///'+'Carton ID ##:'+'#G'
	lcStringBlock1=lcStringBlock1+'#T110.0#J'+str(lnOffset+12)+'#YT103/2///'+left(carton_num,20)+'#G'
	lcStringBlock1=lcStringBlock1+'#T66.6#J'+str(lnOffset+12)+'#YT103/2///'+'PO ##:'+'#G'
	lcStringBlock1=lcStringBlock1+'#T58.0#J'+str(lnOffset+12)+'#YT103/2///'+allt(po_num)+'#G'
	lcStringBlock1=lcStringBlock1+'#T28.0#J'+str(lnOffset+12)+'#YT103/2///'+'P/S##: '+allt(STR(pick_num))+'#G'

	*- Header line 3b
	lcStringBlock1=lcStringBlock1+'#T165.0#J'+STR(lnOffset+15)+'#YT103/2///'+'Start Date:'+'#G'
	lcStringBlock1=lcStringBlock1+'#T150.0#J'+STR(lnOffset+15)+'#YT103/2///'+ALLTRIM(DTOC(start_date))+'#G'
	lcStringBlock1=lcStringBlock1+'#T90.0#J'+STR(lnOffset+15)+'#YT103/2///'+'End Date:'+'#G'
	lcStringBlock1=lcStringBlock1+'#T75.0#J'+STR(lnOffset+15)+'#YT103/2///'+ALLTRIM(DTOC(end_date))+'#G'
	
	*--- TR 1012146 - 07/27/05 - BD - Modification 6 = print size_code when size_code is changing
	*--- Bruno DIEPENDAELE -> Mike Sabal = This is a new block of code. Please check the printer control characters
	*- Header line 3c = detail band header
	IF curPart1.size_code<>lcCurSize_code
		*- Print the Size Code
		lcStringBlock1=lcStringBlock1+'#T200.0#J'+str(lnOffset+15)+'#YT103/2///'+'Size Code:'+'#G'
		lcStringBlock1=lcStringBlock1+'#T180.0#J'+str(lnOffset+15)+'#YT103/2///'+left(size_code,3)+'#G'
	ENDIF
	*=== TR 1012146 - BD - End of modification 6

	*- Header line 4 = detail band header
	*lcStringBlock1=lcStringBlock1+SPACE(5)
	lcStringBlock1=lcStringBlock1+'#T200.0#J'+str(lnOffset+18)+'#YT102/2///'+'Style'+'#G'
	lcStringBlock1=lcStringBlock1+'#T182.0#J'+str(lnOffset+18)+'#YT102/2///'+'Color'+'#G'
	lcStringBlock1=lcStringBlock1+'#T170.0#J'+str(lnOffset+18)+'#YT102/2///'+'Price'+'#G'
	lcStringBlock1=lcStringBlock1+'#T160.0#J'+str(lnOffset+18)+'#YT102/2///'+'Label'+'#G'
	*- Maximum 9 size headers
	lnIndValidBucket=0
	for lnIndbucket=1 to 9
		lcIndbucket=TRANS(lnIndbucket,"@L 99")
		*if eval('curPart1.siz'+lcIndbucket+'_qty')>0 and lnIndValidBucket<10
			lcStringBlock1=lcStringBlock1+ ;
				'#T'+str(160-(lnIndbucket*13.3))+'#J'+str(lnOffset+18)+'#YT102/2///'+ ;
				padl(eval('curPart1.siz'+lcIndbucket+'_head'),7)+'#G'
			lnIndValidBucket=lnIndValidBucket+1
		*endif
	endfor
	*- Total
	lcStringBlock1=lcStringBlock1+'#T26.6#J'+str(lnOffset+18)+'#YT102/2///'+'Total'+'#G'
	lcStringBlock1=lcStringBlock1+'#T13.3#J'+STR(lnOffset+18)+'#YT102/2///'+'Retail'+'#G'
	*- Ship To
	*lcStringBlock1=lcStringBlock1+'Ship To:'+SPACE(3)+CRLF


	lnIndLineBlock1=0
	DO WHILE !eof('curPart1') AND lnIndLineBlock1<=MaxNbLineBlock1
		*- Detail line
		*- -----------

		*--- TR 1012146 - 07/27/05 - BD - Modification 7 = print size_code when size_code is changing
		*--- Bruno DIEPENDAELE -> Mike Sabal = This is a new block of code. Please check the printer control characters
		IF curPart1.size_code<>lcCurSize_code
			
			IF lnIndLineBlock1<=MaxNbLineBlock1-2
				*- go to the next line
				lnIndLineBlock1=lnIndLineBlock1+1
			ELSE
				*- Exit from loop ==> go back to printing the main page header 
				exit	
			ENDIF
			lnIndLineBlock1=lnIndLineBlock1-1
			
			*- Print the Size Code
			lcStringBlock1=lcStringBlock1+'#T200.0#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT102/2///'+'Size Code:'+'#G'
			lcStringBlock1=lcStringBlock1+'#T180.0#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT102/2///'+left(size_code,3)+'#G'
			*- go to the next line
			lnIndLineBlock1=lnIndLineBlock1+1
			
			*- Reprint the size header line
			lcStringBlock1=lcStringBlock1+'#T200.0#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT102/2///'+'Style'+'#G'
			lcStringBlock1=lcStringBlock1+'#T186.6#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT102/2///'+'Color'+'#G'
			lcStringBlock1=lcStringBlock1+'#T173.3#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT102/2///'+'Price'+'#G'
			lcStringBlock1=lcStringBlock1+'#T160.0#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT102/2///'+'Label'+'#G'
			*- Maximum 9 size headers
			lnIndValidBucket=0
			for lnIndbucket=1 to 9
				lcIndbucket=TRANS(lnIndbucket,"@L 99")
				*if eval('curPart1.siz'+lcIndbucket+'_qty')>0 and lnIndValidBucket<10
					lcStringBlock1=lcStringBlock1+ ;
						'#T'+str(160-(lnIndbucket*13.3))+'#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT102/2///'+ ;
						padl(eval('curPart1.siz'+lcIndbucket+'_head'),7)+'#G'
					lnIndValidBucket=lnIndValidBucket+1
				*endif
			endfor
			*- Total
			lcStringBlock1=lcStringBlock1+'#T26.6#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT102/2///'+'Total'+'#G'
			lcStringBlock1=lcStringBlock1+'#T13.3#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT102/2///'+'Retail'+'#G'
			lnIndLineBlock1=lnIndLineBlock1+1

		ENDIF
		*=== TR 1012146 - BD - End of modification 7		
		
		*- Style
		lcStringBlock1=lcStringBlock1+'#T200.0#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT103/2///'+ ;
			padr(style,10)+'#G'
		
		*- Color
		lcStringBlock1=lcStringBlock1+'#T182.0#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT103/2///'+ ;
			padr(color_code,6)+'#G'

		*- Price= do backend query to get price from zzoordrd
		lnPrice=vl_pickdtlsku(pick_num,'price','',style,color_code,lbl_code,dimension)
		lcStringBlock1=lcStringBlock1+'#T170.0#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT103/2///'+ ;
			padr(str(lnprice,6,2),6)+'#G'

		*- Label
		lcStringBlock1=lcStringBlock1+'#T160.0#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT103/2///'+ ;
			padr(lbl_code,6)+'#G'

		*- Bucket quantities
		lnTotal_qty=0
		lnIndValidBucket=0
		for lnIndbucket=1 to 9
			lcIndbucket=TRANS(lnIndbucket,"@L 99")
			*if eval('curPart1.siz'+lcIndbucket+'_qty')>0 and lnIndValidBucket<10
				lcStringBlock1=lcStringBlock1+ '#T'+str(160-(lnIndbucket*13.3))+'#J'+ ;
					str(lnOffset+21+(lnIndLineBlock1*4))+'#YT103/2///'+ ;
					padl(allt(str(eval('curPart1.siz'+lcIndbucket+'_qty'))),7)+"#G"
				lnTotal_qty=lnTotal_qty+eval('curPart1.siz'+lcIndbucket+'_qty')
				lnIndValidBucket=lnIndValidBucket+1
			*endif
		endfor
		
		*- Total
		lcStringBlock1=lcStringBlock1+'#T26.6#J'+str(lnOffset+21+(lnIndLineBlock1*4))+'#YT103/2///'+ ;
			padr(str(lnTotal_qty,6),6)+'#G'
		lcStringBlock1=lcStringBlock1+'#T13.3#J'+STR(lnOffset+21+(lnIndLineBlock1*4))+'#YT103/2///'+ ;
			TRANSFORM(retail1,"999.99")+'#G'
		lnTotalBlockQty = lnTotalBlockQty + lnTotal_qty
		lcShipTo = ALLTRIM(sfsship_name)+': '+ALLTRIM(sfsship_city)+', '+ALLTRIM(sfsship_state)
	
		lnIndLineBlock1=lnIndLineBlock1+1

	 	*--- TR 1012146 - 07/27/05 - BD - Modification 8 = memorize the current size_code being printed
		*--- Bruno DIEPENDAELE -> Mike Sabal = This is a new line of code.
		lcCurSize_code=curPart1.size_code
		*=== TR 1012146 - BD - End of modification 8				

	 	skip 1 in curPart1
	ENDDO 

	*- Send block to printer
	*messagebox(lcStringBlock1)
	*lcStringBlock1=lcStringBlock1+CRLF
	if not eof('curPart1') then
	  ??? lcStringBlock1
	endif

ENDDO		&& End of DO WHILE NOT EOF('curPart1') 

IF AT('#',lcShipTo)>0 AND AT('##',lcShipTo)=0 THEN
  lipos = AT('#',lcShipTo)
  lcShipTo = SUBSTR(lcShipTo,1,lipos-1)+'#'+SUBSTR(lcShipTo,lipos,(LEN(lcShipTo)-lipos)+1)
ENDIF
*- Block 1 summary line
lcStringBlock1=lcStringBlock1+'#T33.3#J'+str(lnOffset+25+(lnIndLineBlock1*4))+'#YT106/2///'+ ;
	'Total: '+str(lnTotalBlockQty)+'#G'
lcStringBlock1=lcStringBlock1+'#T200.0#J'+str(lnOffset+25+(lnIndLineBlock1*4))+'#YT106/2///'+ ;
	'Ship To: '+ alltrim(lcShipTo) + '#G'
if lnPageNum = 3 then
  lcStringBlock1 = lcStringBlock1 + '#Q1#G'
  ??? lcStringBlock1
  ??? "#!A1#IMS203.2/238.0" && 8" wide by 9" long "Page"
  ??? "#ERN1"   
  lnPageNum = 0
else
  ??? lcStringBlock1
endif
  

*- **************************
*- Build PART 2 of the label
*- **************************
*- --------------------------------------------------------------------------------------------------
*- Create cursor CurPart2 
*- --------------------------------------------------------------------------------------------------

select CurPart1
go top

DO WHILE NOT EOF('CurPart1') 

	lnPageNum = lnPageNum + 1
	if lnPageNum > 3 then
	  ??? "#Q1#G"
	  ??? "#!A1#IMS203.2/238.0" && 8" wide by 9" long "Page"
	  ??? "#ERN1"   
	  lnPageNum = 1  
	endif
	lnOffset = (lnPageNum - 1) * 79


	lnThisIsBucket = 0
	FOR lnIndBucket=2 TO 9
		lcIndbucket=TRANSFORM(lnIndbucket,"@L 99")
		lcBktQty = eval('curPart1.siz'+lcIndbucket+'_qty')
		IF lcBktQty > 0 THEN 
			lnThisIsBucket = lnIndBucket
			EXIT
		ENDIF
	ENDFOR 
	lcSKU_UPC = vl_cstdr(curPart1.customer,'CUST_STYLE','',curPart1.division,curPart1.Style,curPart1.color_code,curPart1.lbl_code,curPart1.dimension,curPart1.sizebucket)
	lcCtnCode = vl_cartoncode(pick_num,line_seq,lnThisIsBucket)
	lcPpkCode = ""
	lnAtSign = AT('@',lcCtnCode)
	IF lnAtSign > 0 THEN
	  lcPpkCode = SUBSTR(lcCtnCode,lnAtSign+1)
	  lcCtnCode = SUBSTR(lcCtnCode,1,lnAtSign-1)
	ENDIF
	*- Added substring per Jeff Bechner's request; email dated 8/12/2011
	IF LEN(ALLTRIM(lcSKU_UPC))>14 THEN
		lcSKU_UPC = SUBSTR(lcSKU_UPC,10,4) && Should be chars 10-13, but for some reason it's picking up an extra in the front
	ENDIF
	lcStringBlock2=''
	lcStringBlock2=lcStringBlock2+'#T200.0#J'+str(lnOffset+4)+'#YT107/2///'+ ;
		'P.O.##.: '+ALLTRIM(po_num)+'#G'
	lcStringBlock2=lcStringBlock2+'#T200.0#J'+str(lnOffset+8)+'#YT107/2///'+ ;
		'Style: '+ALLTRIM(lcSKU_UPC)+'#G'
	if len(lcPpkCode)>0 then
		lcStringBlock2=lcStringBlock2+'#T100.0#J'+str(lnOffset+12)+'#YT107/2///'+ ;
		'Prepack code: '+lcPpkCode+'#G'
	endif
	lcStringBlock2=lcStringBlock2+'#T50.0#J'+str(lnOffset+12)+'#YT107/2///'+ ;
		'Carton code: '+lcCtnCode+'#G'
	lnPackCodeBucket = 2

&& Copy part 1 logic for part 2

	*- Header line 4 = detail band header
	lcStringBlock2=lcStringBlock2+'#T200.0#J'+str(lnOffset+18)+'#YT107/2///'+'Color / Size'+'#G'
	*- Maximum 9 size headers
	lnIndValidBucket=0
	lnTotalBlockQty = 0
	lcLastBucket=9
	for lnIndbucket=2 to 9
		lcIndbucket=TRANS(lnIndbucket,"@L 99")
		*if eval('curPart1.siz'+lcIndbucket+'_qty')>0 and lnIndValidBucket<10
			lcStringBlock2=lcStringBlock2+ ;
				'#T'+str(190-(lnIndbucket*13.3))+'#J'+str(lnOffset+18)+'#YT107/2///'+ ;
				padl(eval('curPart1.siz'+lcIndbucket+'_head'),7)+'#G'
			lnIndValidBucket=lnIndValidBucket+1
			if len(alltrim(eval('curPart1.siz'+lcIndbucket+'_head')))=0 then
				lcLastBucket = lnIndbucket - 1
				exit
			endif
		*endif
	endfor
	*- Total
	if LEN(lcPpkCode)>0 then
		lcStringBlock2=lcStringBlock2+'#T57.0#J'+str(lnOffset+15)+'#YT106/2///'+'Total in'+'#G'
		lcStringBlock2=lcStringBlock2+'#T57.0#J'+str(lnOffset+18)+'#YT106/2///'+'Prepack'+'#G'
		lcStringBlock2=lcStringBlock2+'#T37.0#J'+str(lnOffset+15)+'#YT106/2///'+'Number of'+'#G'
		lcStringBlock2=lcStringBlock2+'#T37.0#J'+str(lnOffset+18)+'#YT106/2///'+'Prepacks'+'#G'
	endif
	lcStringBlock2=lcStringBlock2+'#T18.0#J'+str(lnOffset+18)+'#YT106/2///'+'Total'+'#G'


	lnIndLineBlock2=1
	DO WHILE !eof('curPart1') AND lnIndLineBlock2<=MaxNbLineBlock2
		*- Detail line
		*- -----------

		*--- TR 1012146 - 07/27/05 - BD - Modification 7 = print size_code when size_code is changing
		*--- Bruno DIEPENDAELE -> Mike Sabal = This is a new block of code. Please check the printer control characters
		IF curPart1.size_code<>lcCurSize_code
			
			IF lnIndLineBlock2<=MaxNbLineBlock2-2
				*- go to the next line
				lnIndLineBlock2=lnIndLineBlock2+1
			ELSE
				*- Exit from loop ==> go back to printing the main page header 
				exit	
			ENDIF
			lnIndLineBlock2=lnIndLineBlock2-1
			
			*- Print the Size Code
			*lcStringBlock2=lcStringBlock2+'#T200.0#J'+str(lnOffset+21+(lnIndLineBlock2*5))+'#YT102/2///'+left(size_code,3)+'#G'
			*- go to the next line
			*lnIndLineBlock2=lnIndLineBlock2+1
			
			*- Reprint the size header line
			lcStringBlock2=lcStringBlock2+'#T200.0#J'+str(lnOffset+21+(lnIndLineBlock2*5))+'#YT107/2///'+'Color / Size'+'#G'
			*- Maximum 9 size headers
			lnIndValidBucket=0
			for lnIndbucket=2 to lcLastBucket
				lcIndbucket=TRANS(lnIndbucket,"@L 99")
				*if eval('curPart1.siz'+lcIndbucket+'_qty')>0 and lnIndValidBucket<10
					lcStringBlock2=lcStringBlock2+ ;
						'#T'+str(160-(lnIndbucket*13.3))+'#J'+str(lnOffset+21+(lnIndLineBlock2*5))+'#YT107/2///'+ ;
						padl(eval('curPart1.siz'+lcIndbucket+'_head'),7)+'#G'
					lnIndValidBucket=lnIndValidBucket+1
				*endif
			endfor
			*- Total
			lcStringBlock2=lcStringBlock2+'#T18.0#J'+str(lnOffset+21+(lnIndLineBlock2*5))+'#YT107/2///'+'Total'+'#G'
			lnIndLineBlock2=lnIndLineBlock2+1

		ENDIF
		*=== TR 1012146 - BD - End of modification 7		

		getPackHeader(division,size_code,dimension)
		getSizeExplosion(division,size_code,dimension)
		lnPrepack_qty=eval('curPart1.siz01_qty')
		lnNum_Packs = lnPrepack_qty / pack_qty
		lnTotal_qty = lnPrepack_qty
		
		*- Color
		lcCustColor = cust_color(curPart1.customer,curPart1.style,curPart1.color_code)
		lcStringBlock2=lcStringBlock2+'#T200.0#J'+str(lnOffset+21+(lnIndLineBlock2*5))+'#YT107/2///'+ ;
			alltrim(lcCustColor)+'#G'

		*- Bucket quantities
		if pack_qty > 1 then
			lnTotal_qty=0
		endif
		lnIndValidBucket=0
		for lnIndbucket=2 to lcLastBucket
			lcIndbucket=TRANS(lnIndbucket,"@L 99")
			*if eval('curPart1.siz'+lcIndbucket+'_qty')>0 and lnIndValidBucket<10
				lcQtyString = padl(allt(str(eval('curPart1.siz'+lcIndbucket+'_qty'))),7)
				if pack_qty > 1 then
					lcQtyString = padl(allt(str(explarr[lnIndbucket]*lnNum_Packs)),7)
				endif
				lcStringBlock2=lcStringBlock2+ '#T'+str(192-(lnIndbucket*13.3))+'#J'+ ;
					str(lnOffset+21+(lnIndLineBlock2*5))+'#YT107/2///'+ ;
					lcQtyString+"#G"
				if pack_qty > 1 OR lnPrepack_qty = 0 then
					lnTotal_qty=lnTotal_qty+eval('curPart1.siz'+lcIndbucket+'_qty')
				endif
				lnIndValidBucket=lnIndValidBucket+1
			*endif
		endfor
		
		if len(lcPpkCode)>0 then
		liPackSize = 0
*-		lcSQLQuery = "SELECT rng_style,rng_color,rng_lbl,rng_pack,rng_bk FROM zzoordrd WHERE ord_num="+alltrim(str(ord_num))+;
*-			" AND pick_num="+alltrim(str(pick_num))+" AND style='"+alltrim(style)+;
*-			"' AND color_code='"+alltrim(color_code)+"' AND lbl_code='"+alltrim(lbl_code)+"' AND total_qty > 0"
*-			= v_SQLPrep(lcSQLQuery,'RangeStyle','')
*-			if used('RangeStyle') and reccount('RangeStyle')>0 and len(alltrim(RangeStyle.rng_style))>0 then
*-				lcSQLQuery = "SELECT rng_qty FROM zzxrangh WHERE rng_style='"+alltrim(RangeStyle.rng_style)+"' AND rng_color='"+;
*-				alltrim(RangeStyle.rng_color)+"' AND rng_lbl='"+alltrim(RangeStyle.rng_lbl)+"' AND rng_bk="+str(RangeStyle.rng_bk)
*-				= v_SQLPrep(lcSQLQuery,'PackSize','')
*-				if used('PackSize') and reccount('PackSize')>0 then
*-					liPackSize = PackSize.rng_qty
*-				endif
*-			endif
			lcStringBlock2=lcStringBlock2+'#T60.0#J'+str(lnOffset+21+(lnIndLineBlock2*5))+'#YT107/2///'+ ;
				padr(str(pack_qty,6),6)+'#G'
			lcStringBlock2=lcStringBlock2+'#T40.0#J'+str(lnOffset+21+(lnIndLineBlock2*5))+'#YT107/2///'+ ;
				padr(str(lnNum_Packs,6),6)+'#G'
		endif

		*- Total
		lcStringBlock2=lcStringBlock2+'#T20.0#J'+str(lnOffset+21+(lnIndLineBlock2*5))+'#YT107/2///'+ ;
			padr(str(lnTotal_qty,6),6)+'#G'
		lnTotalBlockQty = lnTotalBlockQty + lnTotal_qty
	
		lnIndLineBlock2=lnIndLineBlock2+1

	 	*--- TR 1012146 - 07/27/05 - BD - Modification 8 = memorize the current size_code being printed
		*--- Bruno DIEPENDAELE -> Mike Sabal = This is a new line of code.
		lcCurSize_code=curPart1.size_code
		*=== TR 1012146 - BD - End of modification 8				

	 	skip 1 in curPart1
	ENDDO 

	*- Send one Packing Slip block to the printer
	lcStringBlock2=lcStringBlock2+CRLF
	*messagebox(lcStringBlock2)
	if not eof('curPart1') then
	  ??? lcStringBlock2
	endif	

ENDDO		&& End of DO WHILE NOT EOF('CurPart1') 

*- Block 2 summary line
lcStringBlock2=lcStringBlock2+'#T180.0#J'+str(lnOffset+21+((lnIndLineBlock2+2)*5))+'#YT107/2///'+ ;
	'Qty ___'+ALLTRIM(str(lnTotalBlockQty))+'___ Pieces#G'

*- Check for end of page

if lnPageNum = 3 then
  lcStringBlock2 = lcStringBlock2 + '#Q1#G'
  ??? lcStringBlock2
  ??? "#!A1#IMS203.2/238.0" && 8" wide by 9" long "Page"
  ??? "#ERN1"   
  lnPageNum = 0
else
  ??? lcStringBlock2
endif

*- ***************************************
*- Build PART 3 of the label
*- ***************************************
*- Make all customer specific changes here
*- ***************************************

select CurPart1
go top

*- Christopher & Banks

lnPageNum = lnPageNum + 1
lnOffset = (lnPageNum - 1) * 79
*lnOffset = lnOffset + 3
lcStringBlock3 = ''

*- Draw lines

lcStringBlock3 = lcStringBlock3 + '#T101.6#J'+str(lnOffset+0)+'#YL0/1/1/75#G'
lcStringBlock3 = lcStringBlock3 + '#T101.6#J'+str(lnOffset+35)+'#YL0/2/1/101.6#G'
lcStringBlock3 = lcStringBlock3 + '#T203.2#J'+str(lnOffset+25)+'#YL0/2/1/101.6#G'
lcStringBlock3 = lcStringBlock3 + '#T159.3#J'+str(lnOffset+0)+'#YL0/1/1/25#G'

*- Zone A (Ship from)

lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+2)+'#YT106/2///'+'FROM:'+'#G'
lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+6)+'#YT102/2///'+'LYNN BRANDS, LLC'+'#G'
lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+9)+'#YT102/2///'+'539 JACKSONVILLE RD.'+'#G'
lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+12)+'#YT102/2///'+'WARMINSTER, PA'+'#G'
lcStringBlock3 = lcStringBlock3 + '#T170.0#J'+str(lnOffset+15)+'#YT102/2///'+'18974'+'#G'
lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+21)+'#YT102/2///'+'SO##:'+alltrim(str(ord_num))+;
	'   SD:'+ALLTRIM(DTOC(start_date))+'#G'


*- Zone B (Ship to [DC])

IF alltrim(center_code)<>'D2S' THEN
  B_NAME = alltrim(sfsship_name)
  B_ADDR1 = alltrim(sfsship_addr1)
  B_ADDR2 = alltrim(sfsship_addr2)
  B_CSZ = alltrim(sfsship_city)+', '+alltrim(sfsship_state)+'  '+alltrim(sfsship_zip)
ELSE
  B_NAME = alltrim(sfsstore_name)
  B_ADDR1 = alltrim(sfsmark_addr1)
  B_ADDR2 = alltrim(sfsmark_addr2)
  B_CSZ = alltrim(sfsmark_city)+', '+alltrim(sfsmark_state)+'  '+alltrim(sfsmark_zip)
ENDIF
IF AT('#',B_NAME)>0 AND AT('##',B_NAME)=0 THEN
  lipos = AT('#',B_NAME)
  B_NAME = SUBSTR(B_NAME,1,lipos-1)+'#'+SUBSTR(B_NAME,lipos,(LEN(B_NAME)-lipos)+1)
ENDIF

lcStringBlock3 = lcStringBlock3 + '#T158.0#J'+str(lnOffset+2)+'#YT106/2///'+'TO:'+'#G'
lcStringBlock3 = lcStringBlock3 + '#T155.0#J'+str(lnOffset+9)+'#YT106/2///'+B_NAME+'#G'
lcStringBlock3 = lcStringBlock3 + '#T155.0#J'+str(lnOffset+12)+'#YT106/2///'+B_ADDR1+'#G'
lcStringBlock3 = lcStringBlock3 + '#T155.0#J'+str(lnOffset+15)+'#YT106/2///'+B_ADDR2+'#G'
lcStringBlock3 = lcStringBlock3 + '#T155.0#J'+str(lnOffset+18)+'#YT106/2///'+B_CSZ+'#G'

lcStringBlock3 = lcStringBlock3 + '#T100.0#J'+str(lnOffset+6)+'#YT103/2///'+'Style description:'+'#G'
lcStringBlock3 = lcStringBlock3 + '#T100.0#J'+str(lnOffset+10)+'#YT108/2///'+alltrim(lcStyleName)+'#G'

lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+36)+'#YT108/2///P.O.##.: '+allt(po_num)+'#G'
lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+40)+'#YT108/2///Style: '+allt(lcSKU_UPC)+'#G'
lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+44)+'#YT108/2///Carton Code '+alltrim(lcCtnCode)+'#G'
if len(trim(lcPpkCode))>0 then
	lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+48)+'#YT108/2///Prepack Code '+alltrim(lcPpkCode)+'#G'
endif
lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+52)+'#YT108/2///Made in: _______#G'
lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+60)+'#YT108/2///Carton No.: ________ of ________#G'
lcStringBlock3 = lcStringBlock3 + '#T200.0#J'+str(lnOffset+65)+'#YT108/2///Gross Weight: '+ALLTRIM(str(carton_wgt/2.2,10,2))+' Kgs#G'

&& SSCC-18
lcStringBlock3 = lcStringBlock3 + '#T93.0#J'+str(lnOffset+70)+'#YB15/2M/4/6///'+alltrim(carton_num)+'#G'

*- End

lcStringBlock3 = lcStringBlock3 + '#Q1#G'
??? lcStringBlock3

ENDSCAN		&& End of SCAN curGroupByCarton

select (lnOrgArea)


*- Turn off the printer
SET DEVICE TO SCREEN
SET PRINTER TO

use in CurPart1
use in curGroupByCarton

RETURN .T.


*-----------------------------------------------------------------------------
*- FUNCTION cust_color(customer,style,color)
*- Returns the region code from zzxcslsr
*- Michael J. Sabal, Notations, Inc. 14 Aug 2007
*-----------------------------------------------------------------------------
FUNCTION cust_color 
PARAMETERS parm_customer, parm_style, parm_color

  LOCAL lcSQLQuery, llCount, lcSQLReturn

  lcSQLQuery = "SELECT CUST_COLOR FROM zzxcsthr WHERE customer='"+ ;
               parm_customer+"' AND style='"+parm_style+"' AND "+ ;
               "color_code='"+parm_color+"'"
  = v_SQLPrep(lcSQLQuery,'CustColor','')
  if used('CustColor') and reccount('CustColor')>0
    *- We have a valid customer style x-ref
    lcSQLReturn = CustColor.CUST_COLOR
  else
    lcSQLReturn = parm_color
  endif

RETURN lcSQLReturn

*-----------------------------------------------------------------------------
*- FUNCTION vl_cartoncode(pick_num,line_seq,bucket)
*- Returns assortment from zzeipohd
*- Michael J. Sabal, Notations, Inc. 28 June 2010
*-----------------------------------------------------------------------------
FUNCTION vl_cartoncode
PARAMETERS parm_picknum, parm_lineseq, parm_bucket

  LOCAL lcSQLQuery, llCount, lcSQLReturn

  lcSQLQuery = "SELECT d.assortment FROM zzoordrd d "+;
				"WHERE d.pick_num="+alltrim(str(parm_picknum))+ ;
               " AND d.line_seq="+alltrim(str(parm_lineseq))
  = v_SQLPrep(lcSQLQuery,'poline','')
  if used('poline') and reccount('poline')>0
    *- We have a valid range style
    lcSQLReturn = poline.assortment
  else
  lcSQLQuery = "SELECT d.assortment FROM zzoshprd d "+;
				"WHERE d.pick_num="+alltrim(str(parm_picknum))+ ;
               " AND d.line_seq="+alltrim(str(parm_lineseq))
  = v_SQLPrep(lcSQLQuery,'poline','')
  if used('poline') and reccount('poline')>0
    *- We have a valid range style
    lcSQLReturn = poline.assortment
  else
    lcSQLReturn = ""
	endif
	endif
	&& Oops - EDI processing has left us with a few holes from February 2018.  By October, these lines should be safe to remove.
	if len(alltrim(lcSQLReturn))=0 then
		if parm_picknum=31864597 and parm_lineseq=2 and parm_bucket=3 then 
		lcSQLReturn="L01" 
		endif
		if parm_picknum=31864597 and parm_lineseq=2 and parm_bucket=4 then 
		lcSQLReturn="L02" 
		endif
		if parm_picknum=31864597 and parm_lineseq=2 and parm_bucket=5 then 
		lcSQLReturn="L03" 
		endif
		if parm_picknum=31864597 and parm_lineseq=2 and parm_bucket=6 then 
		lcSQLReturn="L04" 
		endif
		if parm_picknum=31864597 and parm_lineseq=1 and parm_bucket=3 then 
		lcSQLReturn="L05" 
		endif
		if parm_picknum=31864597 and parm_lineseq=1 and parm_bucket=4 then 
		lcSQLReturn="L06" 
		endif
		if parm_picknum=31864597 and parm_lineseq=1 and parm_bucket=5 then 
		lcSQLReturn="L07" 
		endif
		if parm_picknum=31864597 and parm_lineseq=1 and parm_bucket=6 then 
		lcSQLReturn="L08" 
		endif
		if parm_picknum=14441305 and parm_lineseq=2 and parm_bucket=3 then 
		lcSQLReturn="L01" 
		endif
		if parm_picknum=14441305 and parm_lineseq=2 and parm_bucket=4 then 
		lcSQLReturn="L02" 
		endif
		if parm_picknum=14441305 and parm_lineseq=2 and parm_bucket=5 then 
		lcSQLReturn="L03" 
		endif
		if parm_picknum=14441305 and parm_lineseq=2 and parm_bucket=6 then 
		lcSQLReturn="L04" 
		endif
		if parm_picknum=14441305 and parm_lineseq=1 and parm_bucket=3 then 
		lcSQLReturn="L05" 
		endif
		if parm_picknum=14441305 and parm_lineseq=1 and parm_bucket=4 then 
		lcSQLReturn="L06" 
		endif
		if parm_picknum=14441305 and parm_lineseq=1 and parm_bucket=5 then 
		lcSQLReturn="L07" 
		endif
		if parm_picknum=14441305 and parm_lineseq=1 and parm_bucket=6 then 
		lcSQLReturn="L08" 
		endif
		if parm_picknum=14441304 and parm_lineseq=3 and parm_bucket=3 then 
		lcSQLReturn="L01" 
		endif
		if parm_picknum=14441304 and parm_lineseq=3 and parm_bucket=4 then 
		lcSQLReturn="L02" 
		endif
		if parm_picknum=14441304 and parm_lineseq=3 and parm_bucket=5 then 
		lcSQLReturn="L03" 
		endif
		if parm_picknum=14441304 and parm_lineseq=3 and parm_bucket=6 then 
		lcSQLReturn="L04" 
		endif
		if parm_picknum=14441304 and parm_lineseq=1 and parm_bucket=3 then 
		lcSQLReturn="L05" 
		endif
		if parm_picknum=14441304 and parm_lineseq=1 and parm_bucket=4 then 
		lcSQLReturn="L06" 
		endif
		if parm_picknum=14441304 and parm_lineseq=1 and parm_bucket=5 then 
		lcSQLReturn="L07" 
		endif
		if parm_picknum=14441304 and parm_lineseq=1 and parm_bucket=6 then 
		lcSQLReturn="L08" 
		endif
		if parm_picknum=31858134 and parm_lineseq=1 and parm_bucket=2 then 
		lcSQLReturn="L01" 
		endif
		if parm_picknum=31858134 and parm_lineseq=1 and parm_bucket=3 then 
		lcSQLReturn="L02" 
		endif
		if parm_picknum=31858134 and parm_lineseq=1 and parm_bucket=4 then 
		lcSQLReturn="L03" 
		endif
		if parm_picknum=31858134 and parm_lineseq=1 and parm_bucket=5 then 
		lcSQLReturn="L04" 
		endif
		if parm_picknum=31858134 and parm_lineseq=4 and parm_bucket=2 then 
		lcSQLReturn="L05" 
		endif
		if parm_picknum=31858134 and parm_lineseq=4 and parm_bucket=3 then 
		lcSQLReturn="L06" 
		endif
		if parm_picknum=31858134 and parm_lineseq=4 and parm_bucket=4 then 
		lcSQLReturn="L07" 
		endif
		if parm_picknum=31858134 and parm_lineseq=4 and parm_bucket=5 then 
		lcSQLReturn="L08" 
		endif
		if parm_picknum=31858135 and parm_lineseq=1 and parm_bucket=2 then 
		lcSQLReturn="L01" 
		endif
		if parm_picknum=31858135 and parm_lineseq=1 and parm_bucket=3 then 
		lcSQLReturn="L02" 
		endif
		if parm_picknum=31858135 and parm_lineseq=1 and parm_bucket=4 then 
		lcSQLReturn="L03" 
		endif
		if parm_picknum=31858135 and parm_lineseq=1 and parm_bucket=5 then 
		lcSQLReturn="L04" 
		endif
		if parm_picknum=31858135 and parm_lineseq=2 and parm_bucket=2 then 
		lcSQLReturn="L05" 
		endif
		if parm_picknum=31858135 and parm_lineseq=2 and parm_bucket=3 then 
		lcSQLReturn="L06" 
		endif
		if parm_picknum=31858135 and parm_lineseq=2 and parm_bucket=4 then 
		lcSQLReturn="L07" 
		endif
		if parm_picknum=31858135 and parm_lineseq=2 and parm_bucket=5 then 
		lcSQLReturn="L08" 
		endif
		if parm_picknum=14441306 and parm_lineseq=1 and parm_bucket=2 then 
		lcSQLReturn="L01" 
		endif
		if parm_picknum=14441306 and parm_lineseq=1 and parm_bucket=3 then 
		lcSQLReturn="L02"
		endif
		if parm_picknum=14441306 and parm_lineseq=1 and parm_bucket=4 then 
		lcSQLReturn="L03" 
		endif
		if parm_picknum=14441306 and parm_lineseq=1 and parm_bucket=5 then 
		lcSQLReturn="L04" 
		endif
		if parm_picknum=14441306 and parm_lineseq=4 and parm_bucket=2 then 
		lcSQLReturn="L05" 
		endif
		if parm_picknum=14441306 and parm_lineseq=4 and parm_bucket=3 then 
		lcSQLReturn="L06" 
		endif
		if parm_picknum=14441306 and parm_lineseq=4 and parm_bucket=4 then 
		lcSQLReturn="L07" 
		endif
		if parm_picknum=14441306 and parm_lineseq=4 and parm_bucket=5 then 
		lcSQLReturn="L08" 
		endif
		if parm_picknum=14441307 and parm_lineseq=1 and parm_bucket=2 then 
		lcSQLReturn="L01" 
		endif
		if parm_picknum=14441307 and parm_lineseq=1 and parm_bucket=3 then 
		lcSQLReturn="L02" 
		endif
		if parm_picknum=14441307 and parm_lineseq=1 and parm_bucket=4 then 
		lcSQLReturn="L03" 
		endif
		if parm_picknum=14441307 and parm_lineseq=1 and parm_bucket=5 then 
		lcSQLReturn="L04" 
		endif
		if parm_picknum=14441307 and parm_lineseq=2 and parm_bucket=2 then 
		lcSQLReturn="L05" 
		endif
		if parm_picknum=14441307 and parm_lineseq=2 and parm_bucket=3 then 
		lcSQLReturn="L06" 
		endif
		if parm_picknum=14441307 and parm_lineseq=2 and parm_bucket=4 then 
		lcSQLReturn="L07" 
		endif
		if parm_picknum=14441307 and parm_lineseq=2 and parm_bucket=5 then 
		lcSQLReturn="L08" 
		endif
	endif

RETURN lcSQLReturn

*-----------------------------------------------------------------------------
*- FUNCTION getPackHeader(division,size_code,dimension)
*-----------------------------------------------------------------------------
PROCEDURE getPackHeader
PARAMETERS Division, size_code, dimension
PUBLIC pack_qty, pack_description
LOCAL lcSQLPackQuery

			*- Get prepack header --*
			lcSQLPackQuery = "SELECT * FROM zzxppakh WHERE division='"+allt(Division)+"' AND size_code='"+ ;
				allt(size_code)+"' AND ppk_code='"+dimension+"'"
			= v_SQLPrep(lcSQLPackQuery,'prepack','')
			if used('prepack') and reccount('prepack')>0 then
				pack_qty = prepack.pack_qty
				pack_description = prepack.ppk_desc
			else
				pack_qty = 1
				pack_description = 'PREPACK'
			endif
RETURN

*-----------------------------------------------------------------------------
*- FUNCTION getSizeExplosion(division,size_code,dimension)
*-----------------------------------------------------------------------------
PROCEDURE getSizeExplosion
PARAMETERS Division, size_code, dimension

LOCAL lcSQL
PUBLIC ARRAY explarr(10)

	lcSQL = "SELECT * FROM zzxppakd WHERE division='"+allt(Division)+"' AND size_code='"+ ;
		allt(size_code)+"' AND ppk_code='"+dimension+"'"
	
	= v_SQLPrep(lcSQL,'explrec','')
  if used('explrec') and reccount('explrec')>0
    *- We have a valid size explosion
	explarr[1] = explrec.pack_total
	explarr[2] = explrec.pack02_qty
	explarr[3] = explrec.pack03_qty
	explarr[4] = explrec.pack04_qty
	explarr[5] = explrec.pack05_qty
	explarr[6] = explrec.pack06_qty
	explarr[7] = explrec.pack07_qty
	explarr[8] = explrec.pack08_qty
	explarr[9] = explrec.pack09_qty
	explarr[10] = explrec.pack10_qty
  endif

RETURN 
